app:
  security:
    jwt:
      secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY"
      access-expiration-ms: 900000        # 15 phút
      refresh-expiration-ms: 604800000    # 7 ngày
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    driver-class-name: org.postgresql.Driver
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: shopdb   # 👈 chỉ định schema mặc định
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # (Day 10 sẽ dùng)
    springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        path: /swagger-ui.html
logging:
  level:
    root: INFO
    com.shop.onlineshop: DEBUG  # chỉ bật DEBUG cho package của bạn
  file:
    name: logs/onlineshop.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"