app:
  security:
    jwt:
      secret: "change-me-to-a-very-long-random-secret-at-least-32-characters"
      expiration-ms: 3600000  # 1h
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    driver-class-name: org.postgresql.Driver
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: shopdb   # 👈 chỉ định schema mặc định
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
